### ISSUE TITLE
Missing property networkProfileArn

### ISSUE THREAD

**Issue by bernedom** [aws-actions/aws-devicefarm-mobile-device-testing#8]
I tried to schedule a DeviceFarm run following the exsmple in the readme. The step always fails with:

`Cannot read properties of undefined (reading 'networkProfileArn')`

The documentarion for the devicefarm says the `networkProfileArn` key in the json is reserved forcinternal use. 

Also we, have no network profiles defined in our devicepool.

**Comment by danjhd** [comment]
Hi, can you supply details of what value you are supplying to the `run-settings-json` property. I suspect it is something about the contents of this property that is causing the error. Please ensure you take care to obfuscate any values you are using,  I am looking to see what properties you are defining rather than their specific values.

**Comment by bernedom** [comment]
We're supplying the following:

```
      - name: Schedule AWS Device Farm Testing
        id: run-device-farm-tests
        uses: aws-actions/aws-devicefarm-mobile-device-testing@v2.0
        # DeviceFarm is only available in us-west-2
        env:
          AWS_REGION: us-west-2
        with:
          run-settings-json: |
            {
              "name": "GitHubAction-${{ github.workflow }}_${{ github.run_id }}_${{ github.run_attempt }}",
              "projectArn": "sky-android-tests",
              "appArn": "build/outputs/apk/debug/app-debug.apk",
              "devicePoolArn": "sky-tests-android-device-pool",
              "test": {
                "type": "APPIUM_NODE",
                "testPackageArn": "e2etest-credentials.txt",
                "testSpecArn": "apps/device-farm-tests.yml"
              }
            }
```

**Comment by bernedom** [comment]
@danjhd  

According to the [docs of the AWS SDK v3 ](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-device-farm/Interface/ScheduleRunCommandInput/) the `networkProfileArn` is no longer present in the `ScheduleRunCommandInput` struct. 

However on [line 346 of index,js](https://github.com/aws-actions/aws-devicefarm-mobile-device-testing/blob/50effc1b45640e1744c64ae9380476f7a131cc3b/index.js#L346) it is passed to the filed `runSettings` which is later passed to the `ScheduleRunCommand` method of the AWS SDK. 

Could it be, that the networkProfile was removed an now causes the error? 

I meanwhile tried passing the networkProfileArn explicitly in several ways,  but none worked. What I tried:
* passing the full ARN as part of  "test" struct in the json
* passing the name of a new profile to look up  "test" struct in the json 
* Passing full ARN and lookup name as field in the root object

**Comment by bernedom** [comment]
I finally got it to run through by using a "configuration" block as described in the tests like this (`myArn` was either the full ARN or a name to look up)
```
      - name: Schedule AWS Device Farm Testing
        id: run-device-farm-tests
        uses: aws-actions/aws-devicefarm-mobile-device-testing@v2.0
        env:
          AWS_REGION: us-west-2
        with:
          run-settings-json: |
            {
              "name": "GitHubAction-${{ github.workflow }}_${{ github.run_id }}_${{ github.run_attempt }}",
              "projectArn": "sky-android-tests",
              "appArn": "apps/app-debug.apk",
              "devicePoolArn": "devicepool",
              
              "test": {
              ...
              },
              "configuration" :{
                "networkProfileArn": "myARN"
              }
            }

  ```

**Comment by danjhd** [comment]
Hi @bernedom, thank you for the extra digging you are doing here. Really appreciated. 

You mentioned that according to the SDK spec the `networkProfileArn` is no longer present in the `ScheduleRunCommandInput` struct. It never was a direct child of that, instead it was (and still is) a child of the `configuration` item, so this is still a valid field. However the link to [Line 346](https://github.com/aws-actions/aws-devicefarm-mobile-device-testing/blob/50effc1b45640e1744c64ae9380476f7a131cc3b/index.js#L346) that you sent is still where the error is, so thank you.

In our checks we are not checking whether the `configuration` property is not being supplied at all (as in your case) so the error is actually because there is no configuration supplied at all, which is a valid thing for you to do so this is a bug we will fix. In the meantime as a workaround you should find that supplying an empty object as the configuration should get you past this error:
```
      - name: Schedule AWS Device Farm Testing
        id: run-device-farm-tests
        uses: aws-actions/aws-devicefarm-mobile-device-testing@v2.0
        # DeviceFarm is only available in us-west-2
        env:
          AWS_REGION: us-west-2
        with:
          run-settings-json: |
            {
              "name": "GitHubAction-${{ github.workflow }}_${{ github.run_id }}_${{ github.run_attempt }}",
              "projectArn": "sky-android-tests",
              "appArn": "build/outputs/apk/debug/app-debug.apk",
              "devicePoolArn": "sky-tests-android-device-pool",
              "test": {
                "type": "APPIUM_NODE",
                "testPackageArn": "e2etest-credentials.txt",
                "testSpecArn": "apps/device-farm-tests.yml"
              },
              "configuration": {}
            }
```

Please let us know if this works for you as a workaround? In the meantime we will address the code changes to fix this.

Thank you.

**Comment by danjhd** [comment]
Release v2.1 has been created that removes the need for the workaround.

**Comment by bernedom** [comment]
@danjhd thanks for fixing it so fast, it fixed my problem.
